# Generated by Django 4.1.6 on 2023-02-18 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_lst_comments_e_mail_lst_comments_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerts',
            old_name='alert_user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='clubs_sports',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='event_user',
            new_name='username',
        ),
    ]
