# Generated by Django 4.1.6 on 2023-02-18 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_alert_user_alerts_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs_sports',
            name='username',
            field=models.ForeignKey(default='VidyaSagar', on_delete=django.db.models.deletion.CASCADE, related_name='Club_sports_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
