# Generated by Django 4.1.6 on 2023-02-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_time_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_table',
            name='branch_tb_img',
            field=models.ImageField(default='static/img.png', upload_to='pics'),
        ),
    ]
